/**
 * 直接模式
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject1 model module.
 * @module model/InlineObject1
 * @version 1.0.0
 */
class InlineObject1 {
    /**
     * @member {String} phone
     * @type {String}
     */
    phone;
    /**
     * @member {String} robotcodeid
     * @type {String}
     */
    robotcodeid;
    /**
     * @member {String} robotcode
     * @type {String}
     */
    robotcode;
    /**
     * @member {String} code
     * @type {String}
     */
    code;
    /**
     * @member {String} paymentpassword
     * @type {String}
     */
    paymentpassword;

    

    /**
     * Constructs a new <code>InlineObject1</code>.
     * @alias module:model/InlineObject1
     * @param phone {String} 此处传参为空字符串
     * @param robotcodeid {String} 
     * @param robotcode {String} 
     * @param code {String} 
     * @param paymentpassword {String} 该密钥为用户进行链上交互使用，密钥设置长度>9位，且包含0-1 A-B a-b 已经特殊字符[~!@#$%^&*?_+;',./\\|·！￥（）{}：“《》？、，。；’”\"《》…-]+
     */
    constructor(phone, robotcodeid, robotcode, code, paymentpassword) { 
        
        InlineObject1.initialize(this, phone, robotcodeid, robotcode, code, paymentpassword);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phone, robotcodeid, robotcode, code, paymentpassword) { 
        obj['phone'] = phone;
        obj['robotcodeid'] = robotcodeid;
        obj['robotcode'] = robotcode;
        obj['code'] = code;
        obj['paymentpassword'] = paymentpassword;
    }

    /**
     * Constructs a <code>InlineObject1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject1} obj Optional instance to populate.
     * @return {module:model/InlineObject1} The populated <code>InlineObject1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject1();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('robotcodeid')) {
                obj['robotcodeid'] = ApiClient.convertToType(data['robotcodeid'], 'String');
            }
            if (data.hasOwnProperty('robotcode')) {
                obj['robotcode'] = ApiClient.convertToType(data['robotcode'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('paymentpassword')) {
                obj['paymentpassword'] = ApiClient.convertToType(data['paymentpassword'], 'String');
            }
        }
        return obj;
    }
}



export default InlineObject1;

