/**
 * 直接模式
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

// CommonJS-like environments that support module.exports, like Node.
factory(require('expect.js'), require(process.cwd()+'/src/index'));

'use strict';

var instance;

beforeEach(function() {
  instance = new OpenapiJsClient.DefaultApi();
});

var getProperty = function(object, getter, property) {
  // Use getter method if present; otherwise, get the property directly.
  if (typeof object[getter] === 'function')
    return object[getter]();
  else
    return object[property];
}

var setProperty = function(object, setter, property, value) {
  // Use setter method if present; otherwise, set the property directly.
  if (typeof object[setter] === 'function')
    object[setter](value);
  else
    object[property] = value;
}

describe('DefaultApi', function() {
    describe('isPhoneRegPost', function() {
      it('should call isPhoneRegPost successfully', function(done) {
        //uncomment below and update the code to test isPhoneRegPost
        //instance.isPhoneRegPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('juguguLoginCodeandReturnInfoPost', function() {
      it('should call juguguLoginCodeandReturnInfoPost successfully', function(done) {
        //uncomment below and update the code to test juguguLoginCodeandReturnInfoPost
        //instance.juguguLoginCodeandReturnInfoPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('jugugugRegAndVerifyandReturnInfoPost', function() {
      it('should call jugugugRegAndVerifyandReturnInfoPost successfully', function(done) {
        //uncomment below and update the code to test jugugugRegAndVerifyandReturnInfoPost
        //instance.jugugugRegAndVerifyandReturnInfoPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
});